<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Article;
use Illuminate\Support\Str;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds for Knowledge Base & Blog.
     */
    public function run(): void
    {
        $articles = [
            [
                'title'            => 'Cara Mengatasi Bak Cuci Piring Mampet Akibat Lemak Membeku',
                'slug'             => 'cara-mengatasi-bak-cuci-piring-mampet-akibat-lemak-membeku',
                'excerpt'          => 'Endapan sisa minyak goreng dan lemak masakan sering membeku di belokan leher angsa wastafel dapur. Simak cara melancarkannya tanpa membongkar pipa.',
                'content'          => '<h2>Mengapa Lemak Menjadi Musuh Utama Wastafel Dapur?</h2><p>Saat Anda mencuci piring atau peralatan masak yang berminyak, lemak cair akan ikut terbilas ke dalam saluran air. Begitu masuk ke pipa pembuangan yang bersuhu lebih dingin, minyak dan lemak cair tersebut akan membeku, menempel di dinding pipa, dan menangkap sisa-sisa makanan lainnya.</p><blockquote>"Bilas lemak dengan air mendidih tidak selalu menyelesaikan masalah jika gumpalan minyak sudah mengeras menjadi kerak sabun lilin (soap scum)."</blockquote><h2>3 Metode Ampuh Mengatasi Wastafel Mampet Berlemak</h2><h3>1. Siraman Air Panas + Sabun Cuci Piring Cair</h3><p>Tuangkan setengah botol sabun cuci piring konsentrat ke dalam lubang wastafel, diamkan 15 menit agar meresap ke pori-pori lemak, lalu siram perlahan dengan 1 galon air mendidih.</p><h3>2. Penggunaan Kombinasi Soda Kue dan Cuka</h3><p>Reaksi kimia alami antara baking soda dan cuka menghasilkan gas karbon dioksida yang dapat melonggarkan ikatan lemak pada dinding PVC pipa.</p><h3>3. Pembersihan Mekanis dengan Mesin Rooter Spiral Flexible</h3><p>Jika sumbatan berada lebih dari 3 meter dari saringan, alat rumah tangga biasa tidak akan bisa menjangkaunya. Teknisi Rootera menggunakan mesin spiral tembak yang dapat menghancurkan kerak lemak tanpa merusak pipa.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(2),
                'meta_title'       => 'Solusi Wastafel Dapur Mampet Berlemak | Rootera Plumbing',
                'meta_description' => 'Cara praktis dan profesional melancarkan bak cuci piring wastafel mampet akibat lemak mengeras tanpa bongkar ubin dapur.',
                'views'            => 342,
            ],
            [
                'title'            => 'Kenapa Air Got Meluap ke Kamar Mandi Saat Hujan Deras?',
                'slug'             => 'kenapa-air-got-meluap-ke-kamar-mandi-saat-hujan-deras',
                'excerpt'          => 'Banjir lokal di kamar mandi saat hujan turun lebat sering disebabkan oleh masalah backflow pada pipa pembuangan utama. Pelajari penyebab & solusinya.',
                'content'          => '<h2>Fenomena Backflow Saluran Air Rumah</h2><p>Pernahkah Anda mengalami air got keluar meluap dari lubang floor drain kamar mandi saat luar rumah sedang hujan deras? Hal ini dipicu oleh tekanan balik (backflow) ketika saluran drainase lingkungan meluap melebihi kapasitasnya.</p><h2>Penyebab Utama Air Got Masuk ke Dalam Rumah</h2><ul><li><strong>Tingkat Kemiringan Pipa (Slope) Kurang Tepat:</strong> Kemiringan pipa pembuangan di bawah standar 2% membuat aliran air lambat saat beban puncak.</li><li><strong>Penumpukan Endapan Pasir & Daun:</strong> Got luar tersumbat sampah sehingga mencari celah terendah di rumah warga.</li><li><strong>Tidak Adanya Katup Backwater Valve:</strong> Saluran buang tidak dilengkapi katup satu arah (one-way valve).</li></ul><h2>Solusi Permanen Mencegah Luapan Air Hujan</h2><p>Pemasangan Backwater Valve modern pada pipa buang utama akan menutup secara otomatis jika ada aliran balik dari saluran got luar. Konsultasikan pemasangan sistem ini dengan tim profesional Rootera.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(5),
                'meta_title'       => 'Penyebab Air Got Meluap ke Kamar Mandi | Rootera',
                'meta_description' => 'Mengapa air got meluap ke kamar mandi saat hujan lebat? Simak penjelasan teknis dan cara penanganan dari Rootera Plumbing.',
                'views'            => 289,
            ],
            [
                'title'            => 'Keunggulan Rooter Spiral Cable vs Kimia Pembersih Saluran Pipa',
                'slug'             => 'keunggulan-rooter-spiral-cable-vs-kimia-pembersih-saluran-pipa',
                'excerpt'          => 'Hati-hati menggunakan soda api atau bahan kimia keras! Kenali bahaya pipa PVC melengkung dan bandingkan dengan metode mechanical rooter spiral.',
                'content'          => '<h2>Bahaya Tersembunyi Bahan Kimia Pembersih Pipa</h2><p>Banyak pemilik rumah langsung membeli soda api atau bahan kimia asam cair ketika pipa mampet. Padahal, reaksi eksotermik (panas tinggi) dari soda api sering kali melunakkan dan membengkokkan sambungan pipa PVC Rucika, memicu kebocoran di dalam dinding.</p><h2>Perbandingan Metode Pembersihan Pipa</h2><h3>1. Cairan Kimia / Soda Api</h3><ul><li>Efektif hanya untuk sumbatan organik tipis.</li><li>Bisa merusak leher angsa dan sambungan lem pipa PVC.</li><li>Berbahaya jika terkena kulit atau terhirup gasnya.</li></ul><h3>2. Mesin Rooter Spiral Cable (Standar Rootera)</h3><ul><li>Kawat spiral baja fleksibel mengikuti lekukan elbow pipa 90 derajat.</li><li>Menjangkau sumbatan hingga kedalaman 30 meter.</li><li>100% aman untuk semua jenis material pipa tanpa bongkar lantai.</li></ul>',
                'author'           => 'Teknisi Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(8),
                'meta_title'       => 'Bahaya Soda Api vs Mesin Rooter Spiral Pipa | Rootera',
                'meta_description' => 'Perbandingan bahaya bahan kimia pembersih pipa dengan keamanan teknologi mesin rooter spiral cable tanpa bongkar.',
                'views'            => 512,
            ],
            [
                'title'            => 'Standar Perawatan Pipa Pembuangan untuk Cafe, Restoran, dan Ruko',
                'slug'             => 'standar-perawatan-pipa-pembuangan-untuk-cafe-restoran-dan-ruko',
                'excerpt'          => 'Bisnis kuliner dan ruko komersial sangat rentan mengalami pipa mampet mendadak yang bisa mengganggu operasional usaha. Ini panduan pemeliharaannya.',
                'content'          => '<h2>Tantangan Operasional Sanitasi Tempat Usaha</h2><p>Satu hari saja wastafel dapur restoran mampet bisa mengakibatkan penghentian operasional dapur dan keluhan dari pelanggan. Oleh karena itu, bisnis kuliner membutuhkan standar pemeliharaan sanitasi rutin.</p><h2>SOP Perawatan Pipa Dapur Komersial</h2><ul><li><strong>Pemasangan Grease Trap Stainless:</strong> Wajib memasang penangkap lemak di bawah sink dan mengurasnya 3 hari sekali.</li><li><strong>Flushing Air Panas Berkala:</strong> Siram saluran dengan air panas setiap malam setelah selesai jam operasional.</li><li><strong>Preventive Maintenance 3 Bulan Sekali:</strong> Pembersihan menyeluruh pipa pembuangan dengan pembersihan mekanis Rootera.</li></ul>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(12),
                'meta_title'       => 'Panduan Maintenance Pipa Restoran & Cafe | Rootera',
                'meta_description' => 'Standar SOP pemeliharaan pipa pembuangan untuk cafe, restoran, dan gedung ruko agar bebas dari masalah mampet mendadak.',
                'views'            => 198,
            ],
            [
                'title'            => 'Solusi Saluran Pembuangan Kamar Mandi Mampet Tanpa Bongkar Lantai',
                'slug'             => 'solusi-saluran-pembuangan-kamar-mandi-mampet-tanpa-bongkar-lantai',
                'excerpt'          => 'Mengatasi genangan air kamar mandi tidak harus membongkar ubin keramik yang mahal. Temukan metode modern pembersihan saluran dari dalam.',
                'content'          => '<h2>Masalah Utama Floor Drain Tersumbat</h2><p>Genangan air di kamar mandi membuat lantai licin dan menjadi sarang kuman. Penyebab terbanyak adalah gumpalan rambut yang mengikat sisa sabun mandi dan kapur air keras.</p><h2>Mengapa Dilarang Membongkar Lantai Sebelum Mencoba Rooter?</h2><p>Banyak pemilik rumah terburu-buru membongkar keramik kamar mandi yang menelan biaya jutaan rupiah. Padahal dengan teknologi rooter fleksibel, sumbatan di dalam saluran dapat ditarik keluar hanya dalam waktu 30-45 menit tanpa merusak ubin selembar pun.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(15),
                'meta_title'       => 'Cara Melancarkan Saluran Kamar Mandi Tanpa Bongkar | Rootera',
                'meta_description' => 'Solusi cepat dan hemat melancarkan floor drain kamar mandi mampet tanpa harus membongkar keramik lantai.',
                'views'            => 410,
            ],
            [
                'title'            => 'Cara Mengatasi Toilet Kloset Duduk Meluap dan Tersumbat',
                'slug'             => 'cara-mengatasi-toilet-kloset-duduk-meluap-dan-tersumbat',
                'excerpt'          => 'Kloset meluap saat disiram? Jangan panik! Pelajari pertolongan pertama dan penanganan masalah leher angsa kloset tersumbat.',
                'content'          => '<h2>Langkah Darurat Saat Kloset Meluap</h2><p>Ketika kloset disiram dan airnya malah naik mendekati bibir kloset, segera matikan suplai air dari stop kran fleksibel di belakang kloset untuk mencegah air meluber ke lantai.</p><h2>Metode Penanganan Kloset Tersumbat</h2><ul><li>Gunakan Plunger khusus toilet berleher karet (flanged plunger).</li><li>Hindari menyiram berulang kali karena akan memperparah luapan.</li><li>Panggil teknisi Rootera jika tersumbat pembalut, tisu basah, atau mainan anak.</li></ul>',
                'author'           => 'Teknisi Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(18),
                'meta_title'       => 'Solusi Kloset Duduk Meluap & Mampet | Rootera Plumbing',
                'meta_description' => 'Panduan darurat penanganan kloset toilet meluap dan mampet secara cepat dan higienis dari tim Rootera.',
                'views'            => 380,
            ],
            [
                'title'            => 'Manfaat Inspection Camera (CCTV Pipe) untuk Deteksi Kebocoran Pipa',
                'slug'             => 'manfaat-inspection-camera-cctv-pipe-untuk-deteksi-kebocoran-pipa',
                'excerpt'          => 'Kamera inspeksi saluran pipa memudahkan identifikasi letak sumbatan, kebocoran, atau pecahan pipa di tempat tersembunyi.',
                'content'          => '<h2>Melihat Bagian Dalam Pipa Tanpa Merusak Dinding</h2><p>Teknologi CCTV Pipe Inspection memungkinkan teknisi memasukkan kabel kamera mikro beresolusi tinggi ke dalam pipa pembuangan untuk melihat kondisi riil saluran secara langsung di layar monitor.</p><h2>Keuntungan Menggunakan Kamera Inspeksi Pipa</h2><ul><li>Mengetahui titik presisi lokasi pipa pecah atau tersumbat.</li><li>Mencegah pembongkaran dinding atau lantai di lokasi yang salah.</li><li>Memberikan bukti rekaman video transparan kepada pemilik rumah.</li></ul>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(22),
                'meta_title'       => 'Inspeksi Kamera CCTV Pipa Mampet & Pecah | Rootera',
                'meta_description' => 'Manfaat teknologi kamera CCTV mikro untuk mendeteksi posisi sumbatan dan kebocoran pipa tersembunyi.',
                'views'            => 275,
            ],
            [
                'title'            => 'Bahaya Soda Api untuk Pipa PVC Rucika / Paralon Rumah Anda',
                'slug'             => 'bahaya-soda-api-untuk-pipa-pvc-rucika-paralon-rumah-anda',
                'excerpt'          => 'Soda api bereaksi menghasilkan panas ekstrem yang dapat melelehkan sambungan lem dan merusak pipa paralon PVC.',
                'content'          => '<h2>Reaksi Panas Soda Api pada Material PVC</h2><p>Soda api (Natrium Hidroksida) bereaksi dengan air menghasilkan panas hingga 100°C. Pipa PVC standar perumahan hanya mampu menahan panas maksimal 60°C, sehingga penggunaan soda api berulang akan membuat pipa melengkung dan bocor di dalam tanah.</p>',
                'author'           => 'Teknisi Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(25),
                'meta_title'       => 'Bahaya Soda Api Merusak Pipa PVC Paralon | Rootera',
                'meta_description' => 'Mengapa Anda harus menghindari penggunaan soda api untuk saluran mampet dan alternatif solusi amannya.',
                'views'            => 610,
            ],
            [
                'title'            => 'Panduan Cuci Toren dan Tangki Air Pemukiman & Apartemen',
                'slug'             => 'panduan-cuci-toren-dan-tangki-air-pemukiman-apartemen',
                'excerpt'          => 'Jaga kebersihan air minum keluarga Anda dengan pembersihan rutin penampung air dari jentik nyamuk dan lumut.',
                'content'          => '<h2>Bahaya Toren Air yang Jarang Dibersihkan</h2><p>Endapan lumpur, lumut hijau, dan jentik nyamuk mudah berkembang biak di dasar tangki penampung air yang tidak dibersihkan lebih dari 6 bulan.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(28),
                'meta_title'       => 'Panduan Cuci Toren & Tangki Penampung Air | Rootera',
                'meta_description' => 'Langkah-langkah pembersihan rutin toren air rumah tangga & apartemen untuk menjaga pasokan air bersih higienis.',
                'views'            => 315,
            ],
            [
                'title'            => 'Cara Mengatasi Bau Busuk yang Keluar dari Floor Drain Kamar Mandi',
                'slug'             => 'cara-mengatasi-bau-busuk-yang-keluar-dari-floor-drain-kamar-mandi',
                'excerpt'          => 'Bau tidak sedap dari saluran pembuangan sering disebabkan oleh perangkap air kering atau sisa organik yang membusuk.',
                'content'          => '<h2>Penyebab Utama Bau Saluran Air</h2><p>Gas dari septic tank atau saluran got lingkungan bisa naik ke kamar mandi jika perangkap leher angsa (P-trap) kekurangan air atau pipa pembuangan kotor.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(30),
                'meta_title'       => 'Cara Hilangkan Bau Busuk Floor Drain Kamar Mandi | Rootera',
                'meta_description' => 'Penyebab dan solusi praktis mengeliminasi bau tidak sedap yang keluar dari lubang saluran kamar mandi.',
                'views'            => 445,
            ],
            [
                'title'            => 'Solusi Pipa Pembuangan Air Hujan / Talang Air Mampet Terhalang Daun',
                'slug'             => 'solusi-pipa-pembuangan-air-hujan-talang-air-mampet-terhalang-daun',
                'excerpt'          => 'Saluran talang hujan yang tersumbat daun dan lumpur dapat memicu kebocoran dak beton dan plafon rumah.',
                'content'          => '<h2>Dampak Talang Air Hujan Mampet</h2><p>Saat musim hujan, tumpukan daun kering dan sarang burung di corong talang air membuat air menggenang dan merembes ke plafon rumah.</p>',
                'author'           => 'Teknisi Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(35),
                'meta_title'       => 'Solusi Talang Hujan & Pipa Pembuangan Mampet | Rootera',
                'meta_description' => 'Cara mengatasi pembuangan talang air hujan tersumbat daun kering untuk mencegah kebocoran atap rumah.',
                'views'            => 290,
            ],
            [
                'title'            => 'Tips Merawat Sistem Plumbing Rumah Tangga Agar Awet Puluhan Tahun',
                'slug'             => 'tips-merawat-sistem-plumbing-rumah-tangga-agar-awet-puluhan-tahun',
                'excerpt'          => 'Perencanaan instalasi pipa yang baik dan perawatan berkala menjaga sistem sanitasi rumah bebas masalah dalam jangka panjang.',
                'content'          => '<h2>Kunci Utama Sistem Plumbing Awet</h2><p>Gunakan material pipa paralon berkualiatas, perhatikan kemiringan pipa 2%, dan hindari membuang sampah non-degradable ke dalam kloset atau wastafel.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(40),
                'meta_title'       => 'Tips Merawat Instalasi Pipa Plumbing Rumah | Rootera',
                'meta_description' => 'Panduan komprehensif perawatan rutin instalasi pipa air bersih dan kotor di rumah tangga agar tahan lama.',
                'views'            => 365,
            ],
            [
                'title'            => 'Pentingnya Jadwal Preventive Maintenance Saluran Pipa untuk Restoran dan Cafe',
                'slug'             => 'pentingnya-jadwal-preventive-maintenance-saluran-pipa-untuk-restoran-dan-cafe',
                'excerpt'          => 'Endapan lemak dapur komersial Restoran & Cafe dapat menutup pipa 100% saat jam sibuk. Simak pentingnya SOP Preventive Maintenance berkala.',
                'content'          => '<h2>Tantangan Lemak Dapur Komersial</h2><p>Bisnis kuliner menyumbang limbah lemak jenuh tinggi dari sisa penggorengan dan pembilasan alat masak. Tanpa jadwal maintenance rutin, gumpalan lemak akan mengeras seperti batuan lilin di dalam pipa buang utama.</p><h2>Manfaat Kontrak Maintenance Rutin B2B (Rootera J&J Group)</h2><ul><li><strong>Menghindari Close Down Dapur:</strong> Mencegah bau menyengat dan genangan air lemak di area dapur saat jam operasional pelanggan.</li><li><strong>SLA Response Cepat:</strong> Penanganan skala prioritas oleh teknisi bersertifikat.</li><li><strong>Kelengkapan Berkas Pajak:</strong> Dilengkapi Invoice Resmi (Faktur Pajak PPN) dari holding <strong>J&J Group</strong>.</li></ul>',
                'author'           => 'Corporate B2B Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(1),
                'meta_title'       => 'Preventive Maintenance Pipa Restoran B2B | Rootera Plumbing (J&J Group)',
                'meta_description' => 'Pentingnya jadwal perawatan saluran pipa dapur restoran dan cafe berkala untuk mencegah mampet mendadak saat jam buka.',
                'views'            => 420,
            ],
            [
                'title'            => 'Mengatasi Masalah Main Pipe Clogged pada Gedung Bertingkat dan Apartemen',
                'slug'             => 'mengatasi-masalah-main-pipe-clogged-pada-gedung-bertingkat-dan-apartemen',
                'excerpt'          => 'Pipa tegak vertikal (main stack pipe) apartemen yang mampet berdampak pada luapan air kotor di unit lantai bawah. Ini metode perbaikannya.',
                'content'          => '<h2>Risiko Saluran Pipa Tegak Vertikal Mampet</h2><p>Pada gedung tinggi, seluruh buangan air limbah kamar mandi dan dapur dari puluhan lantai akan bermuara ke pipa buang vertikal utama. Ketika terjadi sumbatan di lantai bawah, gaya gravitasi mendorong luapan air keluar dari floor drain unit lantai terbawah.</p><h2>Metode Penanganan Berstandar Industri</h2><p>Rootera Plumbing (J&J Group) menggunakan alat perontok kerak pipa vertikal berkecepatan tinggi dan kamera inspeksi mikro untuk mengidentifikasi posisi tumpukan sedimen tanpa perlu membongkar dinding cor beton gedung.</p>',
                'author'           => 'Enterprise Plumbing Specialist',
                'status'           => 'published',
                'published_at'     => now()->subDays(3),
                'meta_title'       => 'Penanganan Pipa Mampet Gedung Bertingkat B2B | Rootera (J&J Group)',
                'meta_description' => 'Solusi perbaikan main stack pipe mampet pada gedung bertingkat, apartemen, dan mall tanpa membongkar struktur dinding gedung.',
                'views'            => 380,
            ],
            [
                'title'            => 'Teknologi Hydro Jetting Tekanan Tinggi vs Mesin Spiral Rooter: Kapan Harus Digunakan?',
                'slug'             => 'teknologi-hydro-jetting-tekanan-tinggi-vs-mesin-spiral-rooter',
                'excerpt'          => 'Pelajari perbedaan kegunaan mesin hydro jetting tembak air tekanan tinggi dengan mesin spiral cable kawat baja dalam pelancaran pipa.',
                'content'          => '<h2>Memahami 2 Alat Utama Pelancar Pipa Modern</h2><h3>1. Mesin Flexible Spiral Rooter</h3><p>Sangat ideal untuk perumahan dan ruko dengan diameter pipa 2-4 inci. Kawat spiral baja berputar menghancurkan gumpalan sisa rambut, pembalut, dan lemak tanpa merusak saringan PVC.</p><h3>2. Mesin Hydro Jetting High Pressure</h3><p>Digunakan untuk jaringan pipa komersial & industri diameter 6-12 inci. Semburan air bertekanan hingga 300 Bar membilas bersih kerak minyak dan pasir pembetonan hingga 100% bersih seperti pipa baru.</p>',
                'author'           => 'Tim Ahli Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(6),
                'meta_title'       => 'Hydro Jetting vs Mesin Spiral Rooter Pipa | Rootera Plumbing',
                'meta_description' => 'Perbandingan komprehensif antara teknologi semprot air Hydro Jetting dan Mesin Spiral Rooter untuk perbaikan pipa tersumbat.',
                'views'            => 590,
            ],
            [
                'title'            => 'Panduan Lengkap Standar Saluran Pembuangan Limbah Domestik Pabrik & Industri',
                'slug'             => 'panduan-lengkap-standar-saluran-pembuangan-limbah-domestik-pabrik-dan-industri',
                'excerpt'          => 'Sistem drainase kawasan industri dan pabrik manufaktur membutuhkan baku mutu lingkungan & perawatan bebas karat lumpur.',
                'content'          => '<h2>Regulasi Sanitasi & Drainase Kawasan Industri</h2><p>Pengelolaan limbah cair pabrik harus memenuhi parameter baku mutu sebelum dialirkan ke Instalasi Pengolahan Air Limbah (IPAL) kawasan. Pipa tersumbat lumpur atau sedimen kimia dapat memicu genangan beracun di area produksi.</p><h2>Layanan Pemeliharaan Pipa Industri J&J Group</h2><p>Rootera Plumbing menyediakan paket pemeliharaan drainase industri di kawasan Cikande, Jababeka, MM2100, Karawang, dan Kendal dengan kepatuhan ISO & Faktur Pajak Resmi.</p>',
                'author'           => 'Industrial Sanitation Team',
                'status'           => 'published',
                'published_at'     => now()->subDays(9),
                'meta_title'       => 'Standar Pipa Limbah Industri & Pabrik B2B | Rootera (J&J Group)',
                'meta_description' => 'Panduan pengelolaan dan pemeliharaan rutin saluran limbah cair pabrik manufaktur dan kawasan industri.',
                'views'            => 410,
            ],
            [
                'title'            => 'Tanda-Tanda Pipa Air Bocor di Dalam Dinding dan Cara Mendeteksinya dengan Kamera Inspeksi',
                'slug'             => 'tanda-tanda-pipa-air-bocor-di-dalam-dinding-dan-cara-mendeteksinya',
                'excerpt'          => 'Tagihan air mendadak membengkak? Kenali ciri-ciri pipa pecah dalam tembok beton dan cara mendeteksinya dengan kamera CCTV micro.',
                'content'          => '<h2>Gejala Pipa Bocor Tersembunyi (Hidden Leak)</h2><ul><li>Tagihan PDAM meningkat drastis meskipun pemakaian normal.</li><li>Cat dinding rumah mengelupas, lembap, atau berjamur.</li><li>Pompa air pendorong sering menyala sendiri secara berkala.</li></ul><h2>Deteksi Presisi Tanpa Membongkar Tembok</h2><p>Teknisi Rootera menggunakan kamera inspeksi endoskopik dan detektor tekanan akustik untuk menemukan titik kebocoran hingga skala centimeter, mencegah kerusakan acak pada keramik dinding Anda.</p>',
                'author'           => 'Teknisi Rootera',
                'status'           => 'published',
                'published_at'     => now()->subDays(11),
                'meta_title'       => 'Cara Deteksi Pipa Bocor Dalam Dinding | Rootera Plumbing',
                'meta_description' => 'Kenali tanda-tanda kebocoran pipa air bersih tersembunyi di dalam tembok dan cara melacak posisi persisnya dengan kamera inspeksi.',
                'views'            => 670,
            ],
        ];

        foreach ($articles as $art) {
            Article::updateOrCreate(['slug' => $art['slug']], $art);
        }
    }
}
