<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Gallery;

class GallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $galleries = array (
  0 => 
  array (
    'title' => 'Pelancaran Drainase Kitchen Soichiro Japanese Steakhouse',
    'slug' => 'pelancaran-drainase-kitchen-soichiro-japanese-steakhouse',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-drainase-kitchen-soichiro-steakhouse-jakarta.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-drainase-kitchen-soichiro-steakhouse-jakarta.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Penanganan sumbatan pembekuan lemak pada saluran drainase dapur komersial restoran Soichiro Japanese Steakhouse menggunakan mesin spiral rotary tanpa merusak keramik.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 1,
    'published_at' => '2026-09-02 13:49:46',
  ),
  1 => 
  array (
    'title' => 'Pelancaran Floor Drain Kamar Mandi EM Gelato Blok M',
    'slug' => 'pelancaran-floor-drain-kamar-mandi-em-gelato-blok-m',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-floor-drain-em-gelato-blok-m.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-floor-drain-em-gelato-blok-m.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Selatan',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Proses pengikatan dan pembersihan sisa endapan sabun dan rontokan rambut pada saluran floor drain outlet EM Gelato Blok M.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 2,
    'published_at' => '2026-09-02 13:49:46',
  ),
  2 => 
  array (
    'title' => 'Inspeksi Kamera CCTV Saluran Floor Drain Pertamina Sunter',
    'slug' => 'inspeksi-kamera-cctv-saluran-floor-drain-pertamina-sunter',
    'category' => 'cctv_inspection',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/inspeksi-cctv-floor-drain-pertamina-sunter.webp',
    'media_file_path' => 'images/dokumentasi/inspeksi-cctv-floor-drain-pertamina-sunter.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Utara',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pemeriksaan titik retakan dan letak sumbatan di dalam saluran floor drain Gedung Kantor Pertamina Sunter dengan kamera CCTV fleksibel beresolusi tinggi.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 3,
    'published_at' => '2026-09-02 13:49:46',
  ),
  3 => 
  array (
    'title' => 'Proyek Pelancaran Gutter Restoran Seporsi Mie Kari Jakarta',
    'slug' => 'proyek-pelancaran-gutter-restoran-seporsi-mie-kari-jakarta',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-gutter-seporsi-mie-kari-jakarta.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-gutter-seporsi-mie-kari-jakarta.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pembersihan sampah daun dan kerak minyak goreng pada saluran gutter restoran Seporsi Mie Kari hingga air mengalir lancar kembali.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 4,
    'published_at' => '2026-09-02 13:49:46',
  ),
  4 => 
  array (
    'title' => 'Dokumentasi Proyek Pelancaran Saluran Stasiun KAI Jawa Tengah',
    'slug' => 'dokumentasi-proyek-pelancaran-saluran-stasiun-kai-jawa-tengah',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/dokumentasi-proyek-stasiun-kai-jateng-4.webp',
    'media_file_path' => 'images/dokumentasi/dokumentasi-proyek-stasiun-kai-jateng-4.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Tengah',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Penanganan proyek vital infrastruktur publik di Stasiun KAI Jawa Tengah untuk melancarkan jaringan pembuangan air utama stasiun.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 5,
    'published_at' => '2026-09-02 13:49:46',
  ),
  5 => 
  array (
    'title' => 'Teknisi APD Lengkap Penanganan Sink Pabrik Makanan',
    'slug' => 'teknisi-apd-lengkap-penanganan-sink-pabrik-makanan',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/teknisi-apd-lengkap-sink-pabrik-makanan.webp',
    'media_file_path' => 'images/dokumentasi/teknisi-apd-lengkap-sink-pabrik-makanan.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Indonesia',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Penerapan standar keselamatan kerja K3 dan APD steril dalam pengerjaan pembersihan saluran sink fasilitas produksi pabrik makanan ternama.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 6,
    'published_at' => '2026-09-02 13:49:46',
  ),
  6 => 
  array (
    'title' => 'Before & After Pembersihan Talang Gutter Roof',
    'slug' => 'before-after-pembersihan-talang-gutter-roof',
    'category' => 'before_after',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/after-pembersihan-talang-gutter-rootera.webp',
    'media_file_path' => 'images/dokumentasi/after-pembersihan-talang-gutter-rootera.webp',
    'external_media_url' => NULL,
    'before_image_path' => 'images/dokumentasi/pelancar-saluran-gutter-resto-jakarta.webp',
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Kondisi talang air gutter setelah dibersihkan total dari penumpukan lumpur hitam dan dedaunan busuk.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 7,
    'published_at' => '2026-09-02 13:49:46',
  ),
  7 => 
  array (
    'title' => 'After Pembersihan Gutter Restoran Bersih Tuntas',
    'slug' => 'after-pembersihan-gutter-restoran-bersih-tuntas',
    'category' => 'before_after',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/after-gutter-resto-bersih-rootera.webp',
    'media_file_path' => 'images/dokumentasi/after-gutter-resto-bersih-rootera.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Tampilan saluran gutter restoran setelah pengerjaan pembersihan total tanpa sisa genangan air.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 8,
    'published_at' => '2026-09-02 13:49:46',
  ),
  8 => 
  array (
    'title' => 'Inspeksi CCTV Saluran Dalam Kloset Mampet',
    'slug' => 'inspeksi-cctv-saluran-dalam-kloset-mampet',
    'category' => 'cctv_inspection',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/inspeksi-cctv-saluran-kloset-mampet.webp',
    'media_file_path' => 'images/dokumentasi/inspeksi-cctv-saluran-kloset-mampet.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Penggunaan kamera CCTV pipa untuk memetakan lokasi benda asing atau gumpalan tisu keras di dalam leher angsa kloset.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 9,
    'published_at' => '2026-09-02 13:49:46',
  ),
  9 => 
  array (
    'title' => 'Inspeksi Kamera CCTV Pipa Tersumbat Lemak',
    'slug' => 'inspeksi-kamera-cctv-pipa-tersumbat-lemak',
    'category' => 'cctv_inspection',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/inspeksi-kamera-cctv-pipa-tersumbat.webp',
    'media_file_path' => 'images/dokumentasi/inspeksi-kamera-cctv-pipa-tersumbat.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Tampilan monitor kamera CCTV yang menampilkan akumulasi lemak membatu di dinding dalam pipa pembuangan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 10,
    'published_at' => '2026-09-02 13:49:46',
  ),
  10 => 
  array (
    'title' => 'Pelancaran Floor Drain Kamar Mandi Rumah Tinggal',
    'slug' => 'pelancaran-floor-drain-kamar-mandi-rumah-tinggal',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-floor-drain-kamar-mandi-rumah.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-floor-drain-kamar-mandi-rumah.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Proses pengerjaan pelancaran saringan dan pipa floor drain kamar mandi perumahan secara cepat tanpa membongkar ubin.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 11,
    'published_at' => '2026-09-02 13:49:46',
  ),
  11 => 
  array (
    'title' => 'Pelancaran Saluran Floor Drain Residensial',
    'slug' => 'pelancaran-saluran-floor-drain-residensial',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-saluran-floor-drain-residensial.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-saluran-floor-drain-residensial.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Tangerang',
    'related_service_url' => '/layanan',
    'description' => 'Pengikatan dan pembersihan sumbatan sisa sabun mandi pada saringan floor drain perumahan warga.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 12,
    'published_at' => '2026-09-02 13:49:46',
  ),
  12 => 
  array (
    'title' => 'Pelancar Saluran Gutter Resto Jakarta',
    'slug' => 'pelancar-saluran-gutter-resto-jakarta',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-saluran-gutter-resto-jakarta.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-saluran-gutter-resto-jakarta.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Pembersihan rontokan dedaunan dan sisa minyak yang menyumbat saluran pipa gutter area restoran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 13,
    'published_at' => '2026-09-02 13:49:46',
  ),
  13 => 
  array (
    'title' => 'Pelancar Saluran Kloset Toilet Mampet',
    'slug' => 'pelancar-saluran-kloset-toilet-mampet',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-saluran-kloset-toilet-mampet.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-saluran-kloset-toilet-mampet.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Penanganan kloset tersumbat menggunakan kawat spiral baja anti-gores porselen.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 14,
    'published_at' => '2026-09-02 13:49:46',
  ),
  14 => 
  array (
    'title' => 'Pelancaran Saluran Mampet Area Resto',
    'slug' => 'pelancaran-saluran-mampet-area-resto',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-saluran-mampet-area-resto.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-saluran-mampet-area-resto.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Bekasi',
    'related_service_url' => '/layanan',
    'description' => 'Solusi cepat melancarkan saluran pembuangan limbah cair dapur restoran sebelum jam operasional buka.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 15,
    'published_at' => '2026-09-02 13:49:46',
  ),
  15 => 
  array (
    'title' => 'Mesin Drain Cleaner Pelancar Pipa Modern',
    'slug' => 'mesin-drain-cleaner-pelancar-pipa-modern',
    'category' => 'tools_equipment',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/mesin-drain-cleaner-pelancar-pipa.webp',
    'media_file_path' => 'images/dokumentasi/mesin-drain-cleaner-pelancar-pipa.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Unit mesin spiral drain cleaner standar industri yang digunakan teknisi Rootera Plumbing untuk menghancurkan sumbatan membandel.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 16,
    'published_at' => '2026-09-02 13:49:46',
  ),
  16 => 
  array (
    'title' => 'Proses Ridgid Spiral Floor Drain Kamar Mandi',
    'slug' => 'proses-ridgid-spiral-floor-drain-kamar-mandi',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/proses-ridgid-spiral-floor-drain.webp',
    'media_file_path' => 'images/dokumentasi/proses-ridgid-spiral-floor-drain.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Depok',
    'related_service_url' => '/layanan',
    'description' => 'Pengoperasian kabel spiral rotasi fleksibel menembus belokan pipa floor drain 2 inci.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 17,
    'published_at' => '2026-09-02 13:49:46',
  ),
  17 => 
  array (
    'title' => 'Proses Pelancaran Gutter Restoran Jakarta',
    'slug' => 'proses-pelancaran-gutter-restoran-jakarta',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/proses-pelancaran-gutter-restoran-jakarta.webp',
    'media_file_path' => 'images/dokumentasi/proses-pelancaran-gutter-restoran-jakarta.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Pusat',
    'related_service_url' => '/layanan',
    'description' => 'Teknisi melakukan penetrasi kabel spiral baja ke dalam pipa pembuangan talang air hujan restoran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 18,
    'published_at' => '2026-09-02 13:49:46',
  ),
  18 => 
  array (
    'title' => 'Proyek Pelancaran Saluran Stasiun KAI Jawa 1',
    'slug' => 'proyek-pelancaran-saluran-stasiun-kai-jawa-1',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/proyek-pelancaran-saluran-stasiun-kai-1.webp',
    'media_file_path' => 'images/dokumentasi/proyek-pelancaran-saluran-stasiun-kai-1.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Tengah',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pengerjaan pelancaran jaringan drainase fasilitas publik Stasiun Kereta Api Indonesia di wilayah Jawa.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 19,
    'published_at' => '2026-09-02 13:49:47',
  ),
  19 => 
  array (
    'title' => 'Pembersihan Lemak Bak Kontrol Resto Mampet Total',
    'slug' => 'pembersihan-lemak-bak-kontrol-resto-mampet-total',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pembersihan-lemak-bak-kontrol-resto.webp',
    'media_file_path' => 'images/dokumentasi/pembersihan-lemak-bak-kontrol-resto.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Pengangkatan kerak gumpalan lemak beku yang menyumbat total aliran bak kontrol pembuangan restoran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 20,
    'published_at' => '2026-09-02 13:49:47',
  ),
  20 => 
  array (
    'title' => 'Pelancar Mesin Ridgid Floor Drain Kamar Mandi',
    'slug' => 'pelancar-mesin-ridgid-floor-drain-kamar-mandi',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-mesin-ridgid-floor-drain-kamar-mandi.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-mesin-ridgid-floor-drain-kamar-mandi.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Tangerang Selatan',
    'related_service_url' => '/layanan',
    'description' => 'Pelancaran pipa floor drain kamar mandi rumah tangga dengan kabel spiral baja anti korosi.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 21,
    'published_at' => '2026-09-02 13:49:47',
  ),
  21 => 
  array (
    'title' => 'Pelancaran Bak Kontrol Mesin Ridgid',
    'slug' => 'pelancaran-bak-kontrol-mesin-ridgid',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-bak-kontrol-mesin-ridgid.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-bak-kontrol-mesin-ridgid.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Barat',
    'related_service_url' => '/layanan',
    'description' => 'Pebersihan sisa sampah plastik dan lemak yang menyumbat lubang kontrol pembuangan air hujan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 22,
    'published_at' => '2026-09-02 13:49:47',
  ),
  22 => 
  array (
    'title' => 'Penanganan Bak Kontrol Lemak & Sampah Resto',
    'slug' => 'penanganan-bak-kontrol-lemak-sampah-resto',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/penanganan-bak-kontrol-lemak-sampah-resto.webp',
    'media_file_path' => 'images/dokumentasi/penanganan-bak-kontrol-lemak-sampah-resto.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Penanganan sumbatan kronis bak kontrol komersial agar operasional dapur restoran tidak terganggu.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 23,
    'published_at' => '2026-09-02 13:49:47',
  ),
  23 => 
  array (
    'title' => 'Servis Ridgid Gutter Resto Mampet',
    'slug' => 'servis-ridgid-gutter-resto-mampet',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/servis-ridgid-gutter-resto-mampet.webp',
    'media_file_path' => 'images/dokumentasi/servis-ridgid-gutter-resto-mampet.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Timur',
    'related_service_url' => '/layanan',
    'description' => 'Pembersihan kotoran dan lumpur yang mengendap pada saluran buangan gutter atap restoran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 24,
    'published_at' => '2026-09-02 13:49:47',
  ),
  24 => 
  array (
    'title' => 'Proyek Pelancaran Stasiun KAI Jateng 2',
    'slug' => 'proyek-pelancaran-stasiun-kai-jateng-2',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/proyek-pelancaran-stasiun-kai-jateng-2.webp',
    'media_file_path' => 'images/dokumentasi/proyek-pelancaran-stasiun-kai-jateng-2.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Tengah',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Kelanjutan dokumentasi pembersihan saluran air stasiun KAI untuk menjamin kelancaran sistem drainase fasilitas penumpang.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 25,
    'published_at' => '2026-09-02 13:49:47',
  ),
  25 => 
  array (
    'title' => 'Penanganan Saluran Stasiun KAI Jateng 3',
    'slug' => 'penanganan-saluran-stasiun-kai-jateng-3',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/penanganan-saluran-stasiun-kai-jateng-3.webp',
    'media_file_path' => 'images/dokumentasi/penanganan-saluran-stasiun-kai-jateng-3.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Tengah',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Proses penyedotan dan pembersihan pipa utama drainase bawah tanah di area peron stasiun KAI.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 26,
    'published_at' => '2026-09-02 13:49:47',
  ),
  26 => 
  array (
    'title' => 'Teknisi Pelancar Wastafel Mesin Ridgid',
    'slug' => 'teknisi-pelancar-wastafel-mesin-ridgid',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/teknisi-pelancar-wastafel-mesin-ridgid.webp',
    'media_file_path' => 'images/dokumentasi/teknisi-pelancar-wastafel-mesin-ridgid.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Proses pelancaran saluran wastafel dapur cuci piring tersumbat minyak goreng dan sisa makanan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 27,
    'published_at' => '2026-09-02 13:49:47',
  ),
  27 => 
  array (
    'title' => 'Drain Cleaner Spiral Baja Wastafel Mampet',
    'slug' => 'drain-cleaner-spiral-baja-wastafel-mampet',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/drain-cleaner-spiral-baja-wastafel.webp',
    'media_file_path' => 'images/dokumentasi/drain-cleaner-spiral-baja-wastafel.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Bekasi',
    'related_service_url' => '/layanan',
    'description' => 'Teknisi mengarahkan kawat spiral fleksibel melewati leher pipa afur wastafel dapur.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 28,
    'published_at' => '2026-09-02 13:49:47',
  ),
  28 => 
  array (
    'title' => 'Teknisi Rootera di Stasiun KAI Jawa Tengah',
    'slug' => 'teknisi-rootera-di-stasiun-kai-jawa-tengah',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/teknisi-rootera-stasiun-kai-jateng.webp',
    'media_file_path' => 'images/dokumentasi/teknisi-rootera-stasiun-kai-jateng.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Tengah',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Tim teknisi spesialis Rootera bertugas di lokasi stasiun KAI Jawa Tengah.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 29,
    'published_at' => '2026-09-02 13:49:47',
  ),
  29 => 
  array (
    'title' => 'Pelancar Bak Kontrol Perumahan Warga',
    'slug' => 'pelancar-bak-kontrol-perumahan-warga',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-bak-kontrol-perumahan-warga.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-bak-kontrol-perumahan-warga.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Tangerang',
    'related_service_url' => '/layanan',
    'description' => 'Pembersihan total endapan tanah lumpur pada bak kontrol luar rumah perumahan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 30,
    'published_at' => '2026-09-02 13:49:47',
  ),
  30 => 
  array (
    'title' => 'Pelancar Saluran Pertamina Sunter Jakarta',
    'slug' => 'pelancar-saluran-pertamina-sunter-jakarta',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancar-saluran-pertamina-sunter-jakarta.webp',
    'media_file_path' => 'images/dokumentasi/pelancar-saluran-pertamina-sunter-jakarta.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Utara',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pengerjaan pelancaran jaringan floor drain di gedung pertamina Sunter Jakarta Utara.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 31,
    'published_at' => '2026-09-02 13:49:47',
  ),
  31 => 
  array (
    'title' => 'Pelancaran Kloset Spiral Baja Profesional',
    'slug' => 'pelancaran-kloset-spiral-baja-profesional',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-kloset-spiral-baja-profesional.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-kloset-spiral-baja-profesional.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Pengerjaan profesional pelancaran kloset tersumbat pembalut / tisu tebal secara cepat dan garansi.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 32,
    'published_at' => '2026-09-02 13:49:47',
  ),
  32 => 
  array (
    'title' => 'Layanan Pelancar Saluran Resto Jabodetabek',
    'slug' => 'layanan-pelancar-saluran-resto-jabodetabek',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/layanan-pelancar-saluran-resto-jabodetabek.webp',
    'media_file_path' => 'images/dokumentasi/layanan-pelancar-saluran-resto-jabodetabek.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Layanan prioritas tanggap darurat 24 jam untuk usaha kafe dan restoran di Jabodetabek.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 33,
    'published_at' => '2026-09-02 13:49:47',
  ),
  33 => 
  array (
    'title' => 'Pembersihan Grease Trap Restoran',
    'slug' => 'pembersihan-grease-trap-restoran',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pembersihan-grease-trap-restoran.webp',
    'media_file_path' => 'images/dokumentasi/pembersihan-grease-trap-restoran.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pembersihan dan pelancaran kotak grease trap penyaring minyak dapur restoran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 34,
    'published_at' => '2026-09-02 13:49:47',
  ),
  34 => 
  array (
    'title' => 'Solusi Bak Kontrol Mampet Operasional Resto',
    'slug' => 'solusi-bak-kontrol-mampet-operasional-resto',
    'category' => 'commercial_resto',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/solusi-bak-kontrol-mampet-operasional-resto.webp',
    'media_file_path' => 'images/dokumentasi/solusi-bak-kontrol-mampet-operasional-resto.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Solusi cepat penanganan luapan bak kontrol resto agar aktivitas dapur kembali higienis.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 35,
    'published_at' => '2026-09-02 13:49:47',
  ),
  35 => 
  array (
    'title' => 'Video Inspeksi Kamera CCTV Saluran Wastafel',
    'slug' => 'video-inspeksi-kamera-cctv-saluran-wastafel',
    'category' => 'cctv_inspection',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-inspeksi-cctv-wastafel.webp',
    'media_file_path' => 'videos/dokumentasi/video-inspeksi-cctv-wastafel.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Video rekaman asli pengujian lorong pipa wastafel menggunakan kamera CCTV waterproof untuk mendeteksi lokasi pasti titik sumbatan.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 36,
    'published_at' => '2026-09-02 13:49:47',
  ),
  36 => 
  array (
    'title' => 'Before & After Pembersihan Talang Gutter',
    'slug' => 'before-after-pembersihan-talang-gutter',
    'category' => 'before_after',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/before-pembersihan-talang-gutter.webp',
    'media_file_path' => 'images/dokumentasi/before-pembersihan-talang-gutter.webp',
    'external_media_url' => NULL,
    'before_image_path' => 'images/dokumentasi/before-pembersihan-talang-gutter.webp',
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Kondisi fisik talang gutter sebelum pembersihan total dari penumpukan lumpur hitam dan daun busuk.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 37,
    'published_at' => '2026-09-02 13:49:47',
  ),
  37 => 
  array (
    'title' => 'Inspeksi Kamera CCTV Pipa Gedung Kantor Jakarta',
    'slug' => 'inspeksi-kamera-cctv-pipa-gedung-kantor-jakarta',
    'category' => 'cctv_inspection',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-inspeksi-cctv-gedung-kantor-jakarta.webp',
    'media_file_path' => 'videos/dokumentasi/video-inspeksi-cctv-gedung-kantor-jakarta.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Video rekaman asli pengujian internal pipa buangan gedung perkantoran di Jakarta menggunakan kamera CCTV waterproof.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 38,
    'published_at' => '2026-09-02 13:49:47',
  ),
  38 => 
  array (
    'title' => 'Kondisi Pipa Resto Mall Tersumbat Lemak Pekat',
    'slug' => 'kondisi-pipa-resto-mall-tersumbat-lemak-pekat',
    'category' => 'cctv_inspection',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/kondisi-pipa-lemak-resto-mall-tersumbat.webp',
    'media_file_path' => 'images/dokumentasi/kondisi-pipa-lemak-resto-mall-tersumbat.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Tampilan kondisi bagian dalam pipa pembuangan dapur resto mall yang tersumbat parah oleh pembekuan lemak makanan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 39,
    'published_at' => '2026-09-02 13:49:47',
  ),
  39 => 
  array (
    'title' => 'Pelancaran Saluran Gutter Lemak Restoran Sushi Tei',
    'slug' => 'pelancaran-saluran-gutter-lemak-restoran-sushi-tei',
    'category' => 'commercial_resto',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-pelancaran-gutter-lemak-sushi-tei.webp',
    'media_file_path' => 'videos/dokumentasi/video-pelancaran-gutter-lemak-sushi-tei.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Aksi teknisi Rootera Plumbing melancarkan saluran gutter pembuangan lemak mampet total di outlet Restoran Sushi Tei.',
    'is_featured' => true,
    'is_active' => true,
    'sort_order' => 40,
    'published_at' => '2026-09-02 13:49:47',
  ),
  40 => 
  array (
    'title' => 'Pelancaran Saluran Mampet Area Stasiun Tugu Yogyakarta',
    'slug' => 'pelancaran-saluran-mampet-area-stasiun-tugu-yogyakarta',
    'category' => 'commercial_b2b',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-pelancaran-saluran-stasiun-tugu-yogyakarta.webp',
    'media_file_path' => 'videos/dokumentasi/video-pelancaran-saluran-stasiun-tugu-yogyakarta.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Yogyakarta',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Pengerjaan darurat pelancaran jaringan drainase fasilitas publik Stasiun Kereta Api Tugu Yogyakarta secara tuntas.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 41,
    'published_at' => '2026-09-02 13:49:47',
  ),
  41 => 
  array (
    'title' => 'Pelancaran Kloset Mampet Pabrik Industri',
    'slug' => 'pelancaran-kloset-mampet-pabrik-industri',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-kloset-mampet-pabrik-industri.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-kloset-mampet-pabrik-industri.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Barat',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Penanganan kloset toilet karyawan pabrik mampet total tanpa bongkar menggunakan mesin rotary cable heavy duty.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 42,
    'published_at' => '2026-09-02 13:49:47',
  ),
  42 => 
  array (
    'title' => 'Proyek Pelancaran Saluran Mall Banjarmasin (Part 1)',
    'slug' => 'proyek-pelancaran-saluran-mall-banjarmasin-part-1',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-saluran-mampet-mall-banjarmasin-1.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-saluran-mampet-mall-banjarmasin-1.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Banjarmasin, Kalimantan Selatan',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Ekspansi layanan nasional Rootera Plumbing menangani proyek pelancaran saluran pembuangan utama Mall Banjarmasin.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 43,
    'published_at' => '2026-09-02 13:49:47',
  ),
  43 => 
  array (
    'title' => 'Pelancaran Wastafel Mampet Rumah Warga',
    'slug' => 'pelancaran-wastafel-mampet-rumah-warga',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-wastafel-mampet-rumah-warga.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-wastafel-mampet-rumah-warga.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => '/layanan',
    'description' => 'Pembersihan pipa afur wastafel cuci piring rumah tangga yang tersumbat lemak sisa makanan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 44,
    'published_at' => '2026-09-02 13:49:47',
  ),
  44 => 
  array (
    'title' => 'Pelancaran Saluran Bio Tank Bogor Jawa Barat',
    'slug' => 'pelancaran-saluran-bio-tank-bogor-jawa-barat',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-saluran-bio-tank-bogor-jabar.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-saluran-bio-tank-bogor-jabar.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Bogor, Jawa Barat',
    'related_service_url' => '/layanan',
    'description' => 'Pembersihan penumpukan kerak dan sumbatan pipa outlet pembuangan bio tank di Bogor Jawa Barat.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 45,
    'published_at' => '2026-09-02 13:49:47',
  ),
  45 => 
  array (
    'title' => 'Video Ridgid Pelancaran Saluran Kloset Pabrik Jabar',
    'slug' => 'video-ridgid-pelancaran-saluran-kloset-pabrik-jabar',
    'category' => 'commercial_b2b',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-ridgid-saluran-kloset-pabrik-jabar.webp',
    'media_file_path' => 'videos/dokumentasi/video-ridgid-saluran-kloset-pabrik-jabar.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jawa Barat',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Video rekaman penetrasi kawat auger mesin Ridgid melancarkan toilet komersial pabrik industri di Jawa Barat.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 46,
    'published_at' => '2026-09-02 13:49:47',
  ),
  46 => 
  array (
    'title' => 'Video Ridgid Drain Cleaner Gutter Resto Mie Kari',
    'slug' => 'video-ridgid-drain-cleaner-gutter-resto-mie-kari',
    'category' => 'commercial_resto',
    'media_type' => 'video',
    'thumbnail_path' => 'images/dokumentasi/thumb-video-ridgid-drain-cleaner-gutter-mie-kari.webp',
    'media_file_path' => 'videos/dokumentasi/video-ridgid-drain-cleaner-gutter-mie-kari.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta',
    'related_service_url' => '/layanan',
    'description' => 'Video pengerjaan pembersihan kerak kuah kari dan minyak padat pada gutter buangan resto Seporsi Mie Kari.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 47,
    'published_at' => '2026-09-02 13:49:47',
  ),
  47 => 
  array (
    'title' => 'Pelancaran Saluran Mall Banjarmasin Mesin Ridgid (Part 2)',
    'slug' => 'pelancaran-saluran-mall-banjarmasin-mesin-ridgid-part-2',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'images/dokumentasi/pelancaran-saluran-mall-banjarmasin-mesin-ridgid-2.webp',
    'media_file_path' => 'images/dokumentasi/pelancaran-saluran-mall-banjarmasin-mesin-ridgid-2.webp',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Banjarmasin, Kalimantan Selatan',
    'related_service_url' => '/layanan-b2b-komersial',
    'description' => 'Dokumentasi lanjutan pengikatan kerak limbah pipa gedung pusat perbelanjaan Mall Banjarmasin.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 48,
    'published_at' => '2026-09-02 13:49:47',
  ),
  48 => 
  array (
    'title' => 'Pembersihan dan Pelancaran Saluran Floor Drain Kamar Mandi Menggunakan Mesin Ridgid',
    'slug' => 'pembersihan-dan-pelancaran-saluran-floor-drain-kamar-mandi-menggunakan-mesin-ridgid',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/dokum_1788592942_XfaOu3.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'layanan/pelancaran-saluran-floor-drain-ridgid',
    'description' => 'Telah dilakukan pekerjaan pelancaran dan pembersihan sumbatan pada saluran pembuangan (floor drain) di area toilet komersial. Proses penanganan dilakukan menggunakan mesin pembersih saluran mekanis Ridgid Spiral Drain Cleaner tanpa perlu membongkar struktur keramik maupun lantai.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 49,
    'published_at' => '2026-09-05 06:47:56',
  ),
  49 => 
  array (
    'title' => 'Pelancaran Saluran Pembuangan (Floor Drain) Toilet Menggunakan Mesin Ridgid di EM Gelato',
    'slug' => 'pelancaran-saluran-pembuangan-floor-drain-toilet-menggunakan-mesin-ridgid-di-em-gelato',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/whatsapp-image-2025-04-20-at-005159-1_1788593308_aVV63l.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'pelancaran-saluran-floor-drain-ridgid-em-gelato',
    'description' => 'Telah selesai dilakukan pekerjaan pembersihan dan pelancaran saluran pipa pembuangan (floor drain) di area toilet outlet EM Gelato. Pekerjaan dilakukan secara mekanis menggunakan unit mesin Ridgid Spiral Drain Cleaner tanpa perlu melakukan pembongkaran lantai maupun jalur pipa eksisting.elah selesai dilakukan pekerjaan pembersihan dan pelancaran saluran pipa pembuangan (floor drain) di area toilet outlet EM Gelato. Pekerjaan dilakukan secara mekanis menggunakan unit mesin Ridgid Spiral Drain Cleaner tanpa perlu melakukan pembongkaran lantai maupun jalur pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 50,
    'published_at' => '2026-09-05 07:28:29',
  ),
  50 => 
  array (
    'title' => 'Jasa Pembersihan dan Pelancaran Saluran Pipa Pembuangan Sink Kantor Imigrasi',
    'slug' => 'jasa-pembersihan-dan-pelancaran-saluran-pipa-pembuangan-sink-kantor-imigrasi',
    'category' => 'commercial_b2b',
    'media_type' => 'video',
    'thumbnail_path' => 'images/JnJ.jpeg',
    'media_file_path' => 'galleries/media/Q2CEgeEYdRe0FTUzVUo6hpKFgwU1srymjaneZxjX.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'layanan/jasa-pelancaran-saluran-sink-kantor-imigrasi',
    'description' => 'Pekerjaan pembersihan dan normalisasi jalur pipa pembuangan bak cuci piring (kitchen sink) di area pantry Kantor Imigrasi yang mengalami sumbatan total. Penanganan dilakukan menggunakan mesin electric drain cleaner kabel baja spiral fleksibel tanpa proses pembongkaran pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 51,
    'published_at' => '2026-09-05 07:38:36',
  ),
  51 => 
  array (
    'title' => 'Inspeksi Jalur Saluran Pembuangan Menggunakan Kamera Endoscope CCTV di Pertamina Marine Region',
    'slug' => 'inspeksi-jalur-saluran-pembuangan-menggunakan-kamera-endoscope-cctv-di-pertamina-marine-region',
    'category' => 'commercial_b2b',
    'media_type' => 'video',
    'thumbnail_path' => 'images/JnJ.jpeg',
    'media_file_path' => 'galleries/media/mImsOc39OR0Jk8v20J7jtDsPB6VXTlKdRbUVNWr8.mp4',
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Koja,Jakarta Utara',
    'related_service_url' => 'layanan/inspeksi-pipa-cctv-jakarta',
    'description' => 'Pekerjaan inspeksi visual jalur instalasi pipa pembuangan di area toilet Pertamina Marine Region menggunakan perangkat pipe drain inspection camera. Pemeriksaan ini bertujuan untuk memetakan kondisi fisik dinding dalam pipa secara akurat serta mendeteksi titik sumbatan, endapan kerak, atau anomali pada jalur sambungan.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 52,
    'published_at' => '2026-09-05 07:43:50',
  ),
  52 => 
  array (
    'title' => 'Pembersihan dan Pelancaran Saluran Kitchen Gutter Menggunakan Mesin Ridgid di Sushi Tei Pakuwon Mall Jogja',
    'slug' => 'pembersihan-dan-pelancaran-saluran-kitchen-gutter-menggunakan-mesin-ridgid-di-sushi-tei-pakuwon-mall-jogja',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/gambar-ai-canva-5-sep-2026-144648_1788594662_WUZhjx.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Yogyakarta',
    'related_service_url' => 'layanan/pembersihan-saluran-gutter-jogja',
    'description' => 'Pekerjaan pembersihan dan pelancaran saluran pembuangan kitchen gutter (floor drain stainless steel) di area dapur restoran Sushi Tei, Pakuwon Mall Jogja. Penanganan dilakukan menggunakan unit mesin drain cleaner kawat spiral fleksibel untuk mengatasi sumbatan akibat akumulasi sisa bahan makanan dan endapan lemak tanpa merusak konstruksi lantai maupun instalasi saluran.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 53,
    'published_at' => '2026-09-05 07:51:03',
  ),
  53 => 
  array (
    'title' => 'Pembersihan dan Pelancaran Saluran Pembuangan Floor Drain Toilet di Sekolah Bina Bangsa',
    'slug' => 'pembersihan-dan-pelancaran-saluran-pembuangan-floor-drain-toilet-di-sekolah-bina-bangsa',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/whatsapp-image-2024-08-28-at-005647-2_1788595197_xKBdnz.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Utara',
    'related_service_url' => 'layanan/pembersihan-saluran-floor-drain-jakarta',
    'description' => 'Pekerjaan pembersihan dan pelancaran saluran pipa pembuangan (floor drain) pada bilik toilet Sekolah Bina Bangsa, Penjaringan, Jakarta Utara. Penanganan dilakukan secara mekanis menggunakan mesin spiral drain cleaner tanpa merusak instalasi kloset duduk maupun membongkar lantai keramik.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 07:59:57',
  ),
  54 => 
  array (
    'title' => 'Pembersihan dan Pelancaran Saluran Floor Drain Kamar Mandi Menggunakan Mesin Ridgid di Kebayoran Baru, Jakarta Selatan',
    'slug' => 'pembersihan-dan-pelancaran-saluran-floor-drain-kamar-mandi-menggunakan-mesin-ridgid-di-kebayoran-baru-jakarta-selatan',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/gemini-generated-image-6f9rhm6f9rhm6f9r_1788596958_8nM5LL.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Selatan',
    'related_service_url' => 'layanan/pembersihan-saluran-floor-drain-jakarta-selatan',
    'description' => 'Pekerjaan pembersihan dan pelancaran saluran pembuangan air (floor drain) kamar mandi di kawasan Selong, Kebayoran Baru, Jakarta Selatan. Penanganan dilakukan secara mekanis menggunakan mesin spiral drain cleaner Ridgid tanpa proses pembongkaran lantai keramik maupun instalasi pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 08:29:18',
  ),
  55 => 
  array (
    'title' => 'Pelancaran Saluran Bak Kontrol Mesin Ridgid Jakarta Selatan',
    'slug' => 'pelancaran-saluran-bak-kontrol-mesin-ridgid-jakarta-selatan',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/gemini-generated-image-ntxeo6ntxeo6ntxe_1788597663_LiaIq3.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jakarta Selatan',
    'related_service_url' => 'layanan/pembersihan-saluran-bak-kontrol-jakarta-selatan',
    'description' => 'Pekerjaan pembersihan dan pelancaran sumbatan pada jalur pipa pembuangan bak kontrol (inspection chamber) di area luar/garasi hunian wilayah Jakarta Selatan. Penanganan dilakukan secara mekanis menggunakan mesin spiral drain cleaner Ridgid tanpa perlu membongkar lantai maupun merusak instalasi pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 08:41:04',
  ),
  56 => 
  array (
    'title' => 'Proses Pembersihan dan Pelancaran Saluran Pipa Bak Kontrol Luar Menggunakan Mesin Spiral Ridgid di Area Jabodetabek',
    'slug' => 'proses-pembersihan-dan-pelancaran-saluran-pipa-bak-kontrol-luar-menggunakan-mesin-spiral-ridgid-di-area-jabodetabek',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/whatsapp-image-2025-05-22-at-114556_1788598181_WRKzZ8.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'layanan/pelancaran-saluran-bak-kontrol-jabodetabek',
    'description' => 'Pekerjaan pembersihan dan pelancaran sumbatan pada instalasi pipa bak kontrol luar (outdoor inspection pit) yang mengalami luapan air kotor. Penanganan dilakukan secara mekanis menggunakan unit mesin spiral baja fleksibel Ridgid tanpa perlu membongkar lantai maupun merusak jalur pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 08:49:41',
  ),
  57 => 
  array (
    'title' => 'Proses Pembersihan dan Pelancaran Saluran Gutter Dapur Menggunakan Mesin Ridgid di Resto Gading Serpong',
    'slug' => 'proses-pembersihan-dan-pelancaran-saluran-gutter-dapur-menggunakan-mesin-ridgid-di-resto-gading-serpong',
    'category' => 'commercial_b2b',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/gemini-generated-image-rxm3carxm3carxm3-1_1788598461_wb0DoX.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Tangerang,Banten',
    'related_service_url' => 'layanan/pembersihan-saluran-gutter-tangerang',
    'description' => 'Pekerjaan pembersihan dan pelancaran sumbatan pada saluran pembuangan kitchen gutter di area dapur resto kawasan Gading Serpong. Penanganan dilakukan secara mekanis menggunakan unit mesin drain cleaner spiral baja fleksibel tanpa perlu membongkar lantai dapur maupun merusak jalur instalasi pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 08:54:22',
  ),
  58 => 
  array (
    'title' => 'Proses Pembersihan dan Pelancaran Saluran Floor Drain Kamar Mandi Menggunakan Mesin Ridgid di Area Jabodetabek',
    'slug' => 'proses-pembersihan-dan-pelancaran-saluran-floor-drain-kamar-mandi-menggunakan-mesin-ridgid-di-area-jabodetabek',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/whatsapp-image-2025-07-18-at-010552-1_1788598711_OqGoG2.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'layanan/pembersihan-saluran-floor-drain-jabodetabek',
    'description' => 'Pekerjaan pembersihan dan pelancaran sumbatan pada saluran pembuangan air lantai (floor drain) di area kamar mandi/toilet. Penanganan dilakukan secara mekanis menggunakan unit mesin spiral drain cleaner Ridgid tanpa perlu membongkar lantai keramik maupun merusak instalasi pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 08:58:33',
  ),
  59 => 
  array (
    'title' => 'Proses Pembersihan dan Pelancaran Saluran Bak Kontrol Indoor Menggunakan Mesin Ridgid di Area Jabodetabek',
    'slug' => 'proses-pembersihan-dan-pelancaran-saluran-bak-kontrol-indoor-menggunakan-mesin-ridgid-di-area-jabodetabek',
    'category' => 'residential',
    'media_type' => 'image',
    'thumbnail_path' => 'galleries/thumbnails/whatsapp-image-2025-07-17-at-025824-1_1788598914_SxfIyS.webp',
    'media_file_path' => NULL,
    'external_media_url' => NULL,
    'before_image_path' => NULL,
    'location_tag' => 'Jabodetabek',
    'related_service_url' => 'layanan/pembersihan-saluran-bak-kontrol-jabodetabek',
    'description' => 'Pekerjaan pembersihan dan pelancaran sumbatan pada saluran pembuangan bak kontrol dalam ruangan (indoor access pit / inspection box) di area lantai gedung/komersial. Penanganan dilakukan secara mekanis menggunakan unit mesin spiral drain cleaner Ridgid tanpa perlu membongkar lantai keramik maupun merusak instalasi pipa eksisting.',
    'is_featured' => false,
    'is_active' => true,
    'sort_order' => 0,
    'published_at' => '2026-09-05 09:01:54',
  ),
);

        foreach ($galleries as $item) {
            Gallery::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
